In [3]:
import pandas as pd
baseball = pd.read_html('https://www.baseball-reference.com/leagues/MLB/2019-standard-batting.shtml')
len(baseball)

1

In [4]:
bb_df = baseball[0]
bb_df.head()

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB
0,Arizona Diamondbacks,45,28.7,5.02,162,6315,5633,813,1419,288,...,.434,.757,94,2447,120,70,31,40,36,1119
1,Atlanta Braves,50,28.0,5.28,162,6302,5560,855,1432,277,...,.452,.789,98,2514,104,60,25,35,39,1138
2,Baltimore Orioles,58,26.5,4.50,162,6189,5596,729,1379,252,...,.415,.725,90,2320,111,71,22,37,8,1063
3,Boston Red Sox,47,27.3,5.56,162,6475,5770,901,1554,345,...,.466,.806,106,2688,127,49,20,44,36,1170
4,Chicago Cubs,52,27.7,5.02,162,6195,5461,814,1378,270,...,.452,.783,102,2468,127,83,30,39,33,1071

In [7]:
bb_df[0]["Age"] = bb_df[0]["Age"].astype(int)

KeyError: 0